services:
  - type: web
    name: sneatsnags-frontend
    env: static
    buildCommand: npm install && npm run build:production
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        status: 200
      - type: rewrite
        source: /404.html
        destination: /index.html
        status: 200
    headers:
      # Cache static assets for 1 year
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      # Don't cache HTML files
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://sneatsnags-backend.onrender.com/api
      - key: VITE_APP_NAME
        value: SneatSnags
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        value: pk_test_your_stripe_key
