version: "3"
services:
  app:
    build: .
    container_name: sneatsnags
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sneatsnags
      - JWT_SECRET="your-super-secret-jwt-key-change-this-in-production"
      - JWT_EXPIRES_IN="7d"
      - JWT_REFRESH_SECRET="your-refresh-token-secret"
      - JWT_REFRESH_EXPIRES_IN="30d"
      - NODE_ENV=development
      - PORT=5001
      - SMTP_HOST="smtp.gmail.com"
      - SMTP_PORT=587
      - SMTP_USER=samuelgates271@gmail.com
      - SMTP_PASS=iddafcgebkpqtvfl
      - FROM_EMAIL=samuelgates271@gmail.com
      - FROM_NAME="AutoMatch Tickets"
      - HMAC_VERIFICATION_CODE_SECRET=my_secrete_key
      - FRONTEND_URL="http://localhost:3000"
      - STRIP_SECRET_KEY="sk_test_..."
      - STRIPE_WEBHOOK_SECRET="whsec_..."
      - TICKETMASTER_API_KEY="your-ticketmaster-api-key"
      - TICKETMASTER_API_SECRET="your-ticketmaster-api-secret"
      - MAX_FILE_SIZE=5242880
      - UPLOAD_PATH="/uploads"
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100

    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run dev"

  db:
    image: postgres:13-alpine
    container_name: postgres-db_sneatsnags
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sneatsnags
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
