version: "3"
services:
  app:
    build: .
    container_name: sneatsnags
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sneatsnags
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5001
      - NODE_CODE_SENDING_EMAIL_ADDRESS=samuelgates271@gmail.com
      - NODE_CODE_SENDING_EMAIL_PASSWORD=iddafcgebkpqtvfl
      - HMAC_VERIFICATION_CODE_SECRET=my_secrete_key
    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && node ./index.js"

  db:
    image: postgres:13-alpine
    container_name: postgres-db_sneatsnags
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sneatsnags
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
