version: "3"
services:
  app:
    build: ./backend
    container_name: sneatsnags
    environment:
      # Database Configuration
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sneatsnags

      # JWT Configuration
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_REFRESH_SECRET=your-refresh-token-secret-change-this-in-production
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=7d

      # Server Configuration
      - NODE_ENV=development
      - PORT=5001
      - FRONTEND_URL=http://localhost:5173
      - VITE_API_BASE_URL=http://localhost:5001/api

      # Stripe Configuration (Required for payments)
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key_here
      - STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key_here
      - STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here

      # Email Configuration
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=samuelgates271@gmail.com
      - SMTP_PASS=swsekwdunecbckh
      - FROM_EMAIL=samuelgates271@gmail.com
      - FROM_NAME=SneatSnags Platform

      # Security Configuration
      - HMAC_VERIFICATION_CODE_SECRET=your-hmac-secret-change-this-in-production

      # External API Configuration
      - TICKETMASTER_API_KEY=your-ticketmaster-api-key
      - TICKETMASTER_API_SECRET=your-ticketmaster-api-secret

      # File Upload Configuration
      - MAX_FILE_SIZE=5242880
      - UPLOAD_PATH=/uploads

      # Rate Limiting Configuration
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100

    ports:
      - "5001:5001"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run dev"

  frontend:
    build: ./frontend
    container_name: sneatsnags-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:5001/api
    depends_on:
      - app
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres:13-alpine
    container_name: postgres-db_sneatsnags
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sneatsnags
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
