services:
  - type: web
    name: sneatsnags-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://sneatsnags.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: sneatsnags-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        value: sk_test_your_stripe_secret_key
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_your_webhook_secret
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: samuelgates271@gmail.com
      - key: SMTP_PASS
        value: swsekwdunecbckh
      - key: FROM_EMAIL
        value: samuelgates271@gmail.com
      - key: FROM_NAME
        value: SneatSnags

databases:
  - name: sneatsnags-db
    databaseName: sneatsnags_db
    user: sneatsnags_db_user
