name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: sneatsnags-rg
  AZURE_LOCATION: eastus

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      CONTAINER_REGISTRY_LOGIN_SERVER: ${{ steps.deploy.outputs.containerRegistryLoginServer }}
      BACKEND_URL: ${{ steps.deploy.outputs.backendUrl }}
      FRONTEND_URL: ${{ steps.deploy.outputs.frontendUrl }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create \
          --name ${{ env.AZURE_RESOURCE_GROUP }} \
          --location ${{ env.AZURE_LOCATION }}

    - name: Deploy Infrastructure
      id: deploy
      run: |
        output=$(az deployment group create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --template-file azure-deploy.bicep \
          --parameters azure-deploy.parameters.json \
          --parameters postgresAdminPassword="${{ secrets.POSTGRES_ADMIN_PASSWORD }}" \
          --query 'properties.outputs' \
          --output json)
        
        echo "containerRegistryLoginServer=$(echo $output | jq -r '.containerRegistryLoginServer.value')" >> $GITHUB_OUTPUT
        echo "backendUrl=$(echo $output | jq -r '.backendUrl.value')" >> $GITHUB_OUTPUT
        echo "frontendUrl=$(echo $output | jq -r '.frontendUrl.value')" >> $GITHUB_OUTPUT

  build-and-deploy-backend:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push backend image
      run: |
        # Login to Azure Container Registry
        az acr login --name ${{ needs.deploy-infrastructure.outputs.CONTAINER_REGISTRY_LOGIN_SERVER }}
        
        # Build and push backend image
        cd backend
        docker build -t ${{ needs.deploy-infrastructure.outputs.CONTAINER_REGISTRY_LOGIN_SERVER }}/sneatsnags-backend:latest .
        docker push ${{ needs.deploy-infrastructure.outputs.CONTAINER_REGISTRY_LOGIN_SERVER }}/sneatsnags-backend:latest

    - name: Update backend container app
      run: |
        az containerapp update \
          --name sneatsnags-backend \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --image ${{ needs.deploy-infrastructure.outputs.CONTAINER_REGISTRY_LOGIN_SERVER }}/sneatsnags-backend:latest

  build-and-deploy-frontend:
    needs: [deploy-infrastructure, build-and-deploy-backend]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build frontend with backend URL
      run: |
        cd frontend
        echo "VITE_API_BASE_URL=${{ needs.deploy-infrastructure.outputs.BACKEND_URL }}/api" > .env.production

    - name: Build and push frontend image
      run: |
        # Login to Azure Container Registry
        az acr login --name ${{ needs.deploy-infrastructure.outputs.CONTAINER_REGISTRY_LOGIN_SERVER }}
        
        # Build and push frontend image
        cd frontend
        docker build -t ${{ needs.deploy-infrastructure.outputs.CONTAINER_REGISTRY_LOGIN_SERVER }}/sneatsnags-frontend:latest .
        docker push ${{ needs.deploy-infrastructure.outputs.CONTAINER_REGISTRY_LOGIN_SERVER }}/sneatsnags-frontend:latest

    - name: Update frontend container app
      run: |
        az containerapp update \
          --name sneatsnags-frontend \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --image ${{ needs.deploy-infrastructure.outputs.CONTAINER_REGISTRY_LOGIN_SERVER }}/sneatsnags-frontend:latest

  run-migrations:
    needs: [deploy-infrastructure, build-and-deploy-backend]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run database migrations
      run: |
        az containerapp exec \
          --name sneatsnags-backend \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --command "npx prisma migrate deploy"